spring:
  application:
    name: APIGateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: quiz-service
              uri: lb://QUIZSERVICE
              predicates:
                - Path=/quiz/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: quizCircuitBreaker
                    fallbackUri: forward:/quizFallback
            - id: question-service
              uri: lb://QUESTION-SERVICE
              predicates:
                - Path: /question/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: questionCircuitBreaker
                    fallbackUri: forward:/questionFallback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8070

resilience4j:
  circuitbreaker:
    instances:
      quizCircuitBreaker:
        slidingWindowSize:
          slidingWindowSize: 10
          permittedNumberOfCallsInHalfOpenState: 3
          failureRateThreshold: 50
          waitDurationInOpenState: 10s
      questionCircuitBreaker:
        slidingWindowSize:
          slidingWindowSize: 10
          permittedNumberOfCallsInHalfOpenState: 3
          failureRateThreshold: 50
          waitDurationInOpenState: 10s